### PR TITLE
Check if consensus.db exists before downloading the bootstrap DB

### LINKED ISSUE #10: Skip downloading the bootstrap DB if consensus.db exists
It always tries downloading the bootstrap DB. However, most cases, `consensus.db` already exists because it mounts a local volume to keep Siad's state. It'd be better to check if `consensus.db` exists before downloading the bootstrap DB, and skip it if exists.

### PR DESCRIPTION
**Pull request by jkawamoto**
This PR fixes #10.

### CODE REVIEW

**Comment by perdy** [comment]
In my opinion the flags to control bootstrapping should take priority over that check so, if the app is running with the order to bootstrap consensus.db, it must do it even if it has to replace current db.

**Comment by jkawamoto** [comment]
If the Sia node stops more than one day, it might work to overwrite the current `consensus.db` with the bootstrap DB. But, the local `consensus.db` is usually newer than the bootstrap one, and I'm not sure if we need this overwriting feature. 

On the other hand, restarting the container to update configurations/images happens frequently, and in this case, we wouldn't like to download the DB, since it takes a couple of hours.

**Comment by perdy** [comment]
Let's merge it then :)

**Comment by jkawamoto** [comment]
Thanks!

**Pull request merged**
